export interface ChecklistTemplate {
  id: string
  name: string
  description: string
  items: string[]
}

export const CHECKLIST_TEMPLATES: Record<string, ChecklistTemplate[]> = {
  pl: [
    {
      id: 'poszukiwanie-dzialki',
      name: 'Poszukiwanie i zakup działki',
      description: 'Kluczowe kroki podczas wyboru i zakupu bezpiecznej działki budowlanej',
      items: [
        'Analiza Miejscowego Planu Zagospodarowania Przestrzennego (MPZP) lub WZ',
        'Weryfikacja księgi wieczystej (brak obciążeń, hipotek, służebności)',
        'Weryfikacja dostępu do drogi publicznej (bezpośredni lub służebność drogowa)',
        'Badania geotechniczne gruntu (nośność, poziom wód gruntowych)',
        'Weryfikacja istniejącego uzbrojenia terenu (woda, prąd, gaz, kanalizacja w drodze)',
        'Weryfikacja ukształtowania terenu (spadki, ryzyko zalewania, ukształtowanie)',
        'Ocena otoczenia i uciążliwości (hałas, bliskość stref przemysłowych, odległość od lasu/rzeki)',
        'Sprawdzenie ewidencji gruntów (klasa ziemi rolniczek, np. bonitacja RIII, RIV)',
        'Weryfikacja przebiegu napowietrznych i podziemnych linii energetycznych (strefy ochronne)',
        'Pomiary i wytyczenie granic działki przez uprawnionego geodetę',
        'Negocjacje cenowe i podpisanie umowy przedwstępnej',
        'Podpisanie aktu notarialnego zakupu',
        'Opłacenie podatku PPC u notariusza',
      ],
    },
    {
      id: 'administracja-formalnosci',
      name: 'Administracja i formalności',
      description: 'Etap papierologii od zakupu działki do pozwolenia na budowę',
      items: [
        'Złożenie wniosku o Warunki Zabudowy (WZ) – w przypadku braku MPZP',
        'Wystąpienie o promesę/warunki przyłączenia prądu (PGE/Tauron/itp.)',
        'Wystąpienie o promesę/warunki przyłączenia wody i kanalizacji',
        'Wystąpienie o promesę/warunki przyłączenia gazu (opcjonalnie)',
        'Wybór i zakup projektu gotowego lub zlecenie projektu indywidualnego',
        'Adaptacja projektu gotowego do warunków działki przez architekta adaptującego',
        'Projekt zagospodarowania działki (PZT)',
        'Badanie geologiczne gruntu – dołączenie opinii do projektu budowlanego (jeśli wymagane)',
        'Wyłączenie gruntu z produkcji rolnej/leśnej w starostwie (odrolnienie)',
        'Uzgodnienie wjazdu/zjazdu z drogi z zarządcą drogi (np. ZDW)',
        'Złożenie wniosku o Pozwolenie na Budowę lub zgłoszenie budowy (ze wszystkimi załącznikami)',
        'Odczekanie na uprawomocnienie się decyzji o pozwoleniu na budowę (zazwyczaj 14 dni)',
        'Pobranie i ostemplowanie Dziennika Budowy z urzędu',
        'Zgłoszenie rozpoczęcia robót budowlanych do PINB, minimum 7 dni przed startem prac',
        'Zatrudnienie Kierownika Budowy i złożenie przez niego oświadczenia o podjęciu obowiązków',
      ],
    },
    {
      id: 'przygotowanie-budowy',
      name: 'Przygotowanie działki pod budowę',
      description: 'Fizyczne prace przygotowawcze przed wkopaniem pierwszej łopaty',
      items: [
        'Wyznaczenie stref niebezpiecznych i organizacji ruchu na budowie',
        'Montaż ogrodzenia tymczasowego placu budowy',
        'Zawieszenie żółtej tablicy informacyjnej na widocznym miejscu',
        'Ustawienie zaplecza sanitarnego (Toi-Toi) dla ekipy budowlanej',
        'Zapewnienie dostępu do wody (hydrant, wykopana studnia lub zbiornik z wodą - beczkowóz/mauzer)',
        'Wykonanie tymczasowego przyłącza prądu (RB-tka budowlana obok granicy działki)',
        'Ustawienie blaszaka (kontenera) zabezpieczonego przed włamaniami na drobne narzędzia i cement',
        'Przygotowanie drogi dojazdowej dla ciężkiego sprzętu (nawiezienie i zagęszczenie kruszywa, gruzu lub płyt drogowych)',
        'Karczowanie krzewów i wycinka drzew (jeśli wymagane i uzyskano zgodę)',
        'Odsunięcie i zabezpieczenie wierzchniej warstwy ziemi roślinnej (humusu) na hałdę deponową',
        'Wytyczenie geodezyjne bryły budynku na ławach drutowych przez uprawnionego geodetę (wpis do dziennika)',
        'Zorganizowanie miejsca magazynowania stali zbrojeniowej i materiałów masowych na podkładkach',
        'Przyjaz ekipy odpowiedzialnej za fundamentowanie',
      ],
    },
    {
      id: 'fundamenty-tradycyjne',
      name: 'Fundamenty tradycyjne',
      description: 'Kompletna kontrola jakości fundamentów w technologii tradycyjnej (wylew betonowy lub bloczki)',
      items: [
        'Sprawdź wytyczenie geodezyjne działki i budynku',
        'Zweryfikuj rzędne terenu zgodnie z projektem',
        'Sprawdź wymiary wykopu (szerokość, głębokość)',
        'Zweryfikuj poziom posadowienia (niwelator/łata)',
        'Sprawdź wyrównanie dna wykopu',
        'Zweryfikuj grunt pod fundamentem (nośność, brak nawodnień)',
        'Sprawdź czy usunięto warstwę humusu',
        'Zweryfikuj podsypkę żwirową lub piaskową (grubość)',
        'Sprawdź zbrojenie ław fundamentowych (średnice, rozstaw, grubość otuliny)',
        'Zweryfikuj ciągłość strzemion w ławach',
        'Sprawdź dyblowanie zbrojenia na narożnikach',
        'Zweryfikuj wypusty zbrojeniowe pod ściany',
        'Sprawdź jakość betonu (klasa wg projektu)',
        'Zweryfikuj konsystencję betonu przy dostawie',
        'Sprawdź wylewanie betonu (brak segregacji kruszywa)',
        'Zweryfikuj wibrowanie betonu',
        'Sprawdź czy zachowane wyrównanie powierzchni ław',
        'Zweryfikuj pielęgnację betonu (nawilżanie)',
        'Sprawdź poziom wylanych ław (odchyłka max 2cm)',
        'Zweryfikuj wzajemne powiązanie ław in narożnikach',
        'Sprawdź izolację przeciwwilgociową ław (papa termozgrzewalna lub masa bitumiczna)',
        'Zweryfikuj ciągłość izolacji poziomej',
        'Sprawdź izolację pionową ścian fundamentowych',
        'Zweryfikuj jakość bloczków betonowych (wymiary, klasa)',
        'Sprawdź grubość zaprawy między bloczkami',
        'Zweryfikuj powiązanie bloczków na narożnikach (mijankowe)',
        'Sprawdź pionie i poziome ścian z bloczków',
        'Zweryfikuj szczelność spoin',
        'Sprawdź czy bloczki nie są rozbite lub uszkodzone',
        'Zweryfikuj otworowania w murze (przepusty instalacyjne)',
        'Sprawdź poziom wieńca żelbetowego',
        'Zweryfikuj zbrojenie wieńca (nośność, grubość otuliny)',
        'Sprawdź połączenie wieńca z ławą fundamentową',
        'Zweryfikuj wylew betonu wieńca',
        'Sprawdź izolację termiczną fundamentu (XPS, Styrodur)',
        'Zweryfikuj grubość warstwy izolacji termicznej',
        'Sprawdź drenaż opaskowy lub francuski',
        'Zweryfikuj szczelność drenażu',
        'Sprawdź poziom terenu przy fundamencie (odskok wodny)',
        'Zweryfikuj odprowadzenie wody ze wzgórza skarpy',
        'Sprawdź podkład betonowy pod posadzkę (grubość)',
        'Zweryfikuj wyrównanie podkładu',
        'Sprawdź folię paroizolacyjną pod posadzką',
        'Zweryfikuj ciągłość folii (zakłady, uszczelnienia)',
        'Sprawdź izolację termiczną podposadzkową (styropian, XPS)',
        'Zweryfikuj grubość izolacji termicznej podposadzkowej',
        'Sprawdź wypusty instalacyjne (wod-kan, ogrzewanie)',
        'Zweryfikuj obsypkę wykopu (kruszywo, etapowe zagęszczanie)',
        'Sprawdź zagęszczenie gruntu zagęszczarką',
        'Zweryfikuj poziom terenu po obsypce',
        'Sprawdź brak pęknięć i ubytków w fundamentach przed zasypaniem',
        'Zweryfikuj dokumentację powykonawczą fundamentów',
        'Sprawdź protokół odbioru robót fundamentowych',
        'Zweryfikuj wpis do dziennika budowy przez kierownika',
      ],
    },
    {
      id: 'plyta-fundamentowa',
      name: 'Płyta fundamentowa',
      description: 'Kontrola jakości wykonania płyty fundamentowej (technologia monolityczna)',
      items: [
        'Sprawdź wytyczenie geodezyjne płyty',
        'Zweryfikuj wymiary i kształt płyty zgodnie z projektem',
        'Sprawdź głębokość posadowienia',
        'Zweryfikuj usunięcie warstwy humusu',
        'Sprawdź grunt pod płytą (nośność, brak organiki)',
        'Zweryfikuj podsypkę (kruszywo stabilizowane, grubość min. 15cm)',
        'Sprawdź zagęszczenie podsypki',
        'Zweryfikuj izolację termiczną pod płytą (XPS, min. 15cm)',
        'Sprawdź ułożenie folii paroizolacyjnej (zakłady 20cm, taśmowanie)',
        'Zweryfikuj szalunek obwodowy płyty (prostoliniowość)',
        'Sprawdź zbrojenie dolne płyty (siatka, rozstaw, otulina min 3cm)',
        'Zweryfikuj zbrojenie górne płyty',
        'Sprawdź podkładki dystansowe pod zbrojeniem (beton, nie plastik)',
        'Zweryfikuj wypusty zbrojeniowe pod ściany',
        'Sprawdź przepusty instalacyjne (wod-kan, CO, prąd)',
        'Zweryfikuj zagrzewanie betonu (w warunkach zimowych)',
        'Sprawdź konsystencję betonu przy dostawie (slump test)',
        'Zweryfikuj klasę betonu (co najmniej C20/25 wg projektu)',
        'Sprawdź etapy wylewania i wibrowanie betonu',
        'Zweryfikuj wyrównanie i zatarcie powierzchni',
        'Sprawdź pielęgnację betonu (folią lub mata)',
        'Zweryfikuj poziom ukończonej płyty (odchyłka max 5mm/2m)',
        'Sprawdź brak rys i pęknięć po stwardnieniu',
        'Zweryfikuj brak pustek i kawern w betonie',
        'Sprawdź izolację termiczną obwodową (cokół XPS)',
        'Zweryfikuj ciągłość izolacji obwodowej',
        'Sprawdź uszczelnienie przejść instalacyjnych',
        'Zweryfikuj protokół odbioru płyty fundamentowej',
        'Sprawdź dokumentację fotograficzną zbrojenia przed betonowaniem',
        'Zweryfikuj wpis do dziennika budowy',
      ],
    },
    {
      id: 'stan-surowy-otwarty',
      name: 'Stan surowy otwarty',
      description: 'Kompleksowa kontrola jakości budynku w stanie surowym otwartym (ściany, stropy, dach)',
      items: [
        'Sprawdź oś budynku i wymiary rzutu (geodeta)',
        'Zweryfikuj pionowość ścian zewnętrznych (odchyłka max 1cm/m)',
        'Sprawdź poziom pierwszej warstwy ścian',
        'Zweryfikuj grubość spoin między bloczkami/cegłą',
        'Sprawdź powiązanie bloczków na narożnikach',
        'Zweryfikuj prawidłowość otworu na okna (wymiary, ościeżnice)',
        'Sprawdź prawidłowość otworów drzwiowych',
        'Zweryfikuj nadproża nad otworami (rodzaj, nośność)',
        'Sprawdź zbrojenie nadproży betonowych',
        'Zweryfikuj wypełnienie nadproży prefabrykowanych',
        'Sprawdź wieniec żelbetowy na poziomie stropu (zbrojenie)',
        'Zweryfikuj beton wieńca (klasa, ciągłość)',
        'Sprawdź połączenie wieńca ze ścianami',
        'Zweryfikuj zbrojenie słupów i trzpieni',
        'Sprawdź grubość ścian nośnych (zgodność z projektem)',
        'Zweryfikuj grubość ścian działowych',
        'Sprawdź materiał ścian działowych (cegła silikatowa, bloczki)',
        'Zweryfikuj powiązanie ścian działowych z nośnymi',
        'Sprawdź wypełnienie ścian szczelinowych',
        'Zweryfikuj izolację akustyczną między ścianami',
        'Sprawdź strop żelbetowy monolityczny (zbrojenie dołem i górą)',
        'Zweryfikuj szalunek stropu (szczelność, poziom)',
        'Sprawdź podparcie szalunku (rozstaw podpór)',
        'Zweryfikuj beton stropu (klasa, wibrowanie)',
        'Sprawdź grubość płyty stropowej (wg projektu)',
        'Zweryfikuj strop prefabrykowany (Teriva/Filigran – montaż kierunkowy)',
        'Sprawdź nadbeton na stropie prefabrykowanym',
        'Zweryfikuj otwory w stropie (schody, instalacje)',
        'Sprawdź poziom gotowego stropu (odchyłka max 1cm)',
        'Zweryfikuj brak rys i pęknięć w stropie',
        'Sprawdź belki stropowe drewniane (klasa C24, przekrój wg projektu)',
        'Zweryfikuj rozstaw belek drewnianych',
        'Sprawdź zakotwienie belek w wieńcu',
        'Zweryfikuj impregnację drewna (ognioochronna, grzybochronna)',
        'Sprawdź murłatę (gatunek drewna, połączenia)',
        'Zweryfikuj zakotwienie murłaty do wieńca (kotwy M16)',
        'Sprawdź krokwie (przekrój, rozstaw, nacięcia)',
        'Zweryfikuj kalenicę i płatwie',
        'Sprawdź słupy i miecze więźby dachowej',
        'Zweryfikuj metalowe łączniki więźby (mauerlat, kątowniki)',
        'Sprawdź pionowość słupów więźby',
        'Zweryfikuj symetrię dachu (pomiary przekątnych)',
        'Sprawdź kąt nachylenia połaci (zgodność z projektem)',
        'Zweryfikuj łaty i kontrłaty (wymiary, rozstaw)',
        'Sprawdź folię wstępnego krycia (FWK), klasy W1 lub W3',
        'Zweryfikuj montaż FWK (zakłady, taśmowanie)',
        'Sprawdź pokrycie dachowe (dachówka, blachodachówka)',
        'Zweryfikuj uszczelnienie kalenicowania',
        'Sprawdź mocowanie obróbek blacharskich (rynny, pasy nadrynnowe)',
        'Zweryfikuj odprowadzenie wody z dachu (rury spustowe)',
        'Sprawdź okna dachowe / świetliki (montaż, szczelność)',
        'Zweryfikuj kominy (wymiary, pionowość, głowice)',
        'Sprawdź uszczelnienie przejścia komina przez dach',
        'Zweryfikuj wyłaz dachowy (dostęp, okucia)',
        'Sprawdź schody wewnętrzne lub zewnętrzne',
        'Zweryfikuj poziom podłogi na każdym piętrze',
        'Sprawdź brak pęknięć w ścianach po ciężkich deszczach',
        'Zweryfikuj odwodnienie terenu przy budynku',
        'Sprawdź brak zastoiny wody przy fundamentach',
        'Zweryfikuj zabezpieczenie budynku przed dewastacją (okna, drzwi tymczasowe)',
        'Sprawdź prawidłowość inwentaryzacji geodezyjnej powykonawczej',
        'Zweryfikuj zgodność z projektem budowlanym i warunkami zabudowy',
        'Sprawdź dziennik budowy – wpisy kierownika i inspektora',
        'Zweryfikuj protokół odbioru robót murowych',
        'Sprawdź protokół odbioru stropu',
        'Zweryfikuj protokół odbioru więźby dachowej',
        'Sprawdź protokół odbioru pokrycia dachowego',
        'Zweryfikuj dokumentację fotograficzną poszczególnych etapów',
        'Sprawdź czy budynek jest zawarty w obszarze planu lub WZ',
        'Zweryfikuj zgodność z pozwoleniem na budowę',
        'Sprawdź czy nie przekroczono linii zabudowy',
        'Zweryfikuj odległości od granic działki',
        'Sprawdź projekt pomocniczy (np. obliczenia więźby)',
        'Zweryfikuj czy kierownik budowy jest na bieżąco z dziennikiem',
        'Sprawdź czy materiały posiadają deklaracje właściwości użytkowych',
        'Zweryfikuj certyfikaty wyrobów budowlanych',
        'Sprawdź brak uszkodzeń mechanicznych elementów konstrukcyjnych',
        'Zweryfikuj czystość i porządek na placu budowy',
        'Sprawdź organizację placu budowy (ogrodzenie, tablica)',
        'Zweryfikuj warunki bhp na budowie',
        'Sprawdź zabezpieczenie otworów (ekrany, balustrady tymczasowe)',
        'Zweryfikuj oznakowanie stref niebezpiecznych',
        'Sprawdź stan techniczny rusztowań',
        'Zweryfikuj certyfikaty rusztowań',
        'Sprawdź piorunochron na budowie (jeśl wymagany)',
        'Zweryfikuj licznik energii elektrycznej na budowie',
        'Sprawdź ujęcie wody na budowie',
        'Zweryfikuj węzeł sanitarny dla pracowników',
        'Sprawdź składowisko materiałów budowlanych',
        'Zweryfikuj kontener na odpady budowlane',
      ],
    },
    {
      id: 'okna-drzwi',
      name: 'Okna i drzwi',
      description: 'Kontrola montażu i jakości stolarki okiennej i drzwiowej',
      items: [
        'Sprawdź wymiary okien zgodne z projektem',
        'Zweryfikuj współczynnik U okien (wg dokumentacji, max 0.9 W/m²K)',
        'Sprawdź profil ramy (grubość, komory, klasa)',
        'Zweryfikuj rodzaj szyby (trojszybowa zalecana)',
        'Sprawdź pionowość i poziomość ościeżnicy',
        'Zweryfikuj montaż na łącznikach systemowych (nie na piankę)',
        'Sprawdź montaż paroprzepuszczalnej taśmy od zewnątrz',
        'Zweryfikuj montaż paroizolacyjnej taśmy od wewnątrz',
        'Sprawdź wypełnienie szczelin pianką niskoprzężną',
        'Zweryfikuj poziom parapetu zewnętrznego (odpad wody)',
        'Sprawdź parapet wewnętrzny (mocowanie, uszczelnienie)',
        'Zweryfikuj działanie skrzydeł (otwieranie, zamykanie, uchylanie)',
        'Sprawdź drzwi wejściowe (klasa, RC2 zalecana)',
      ],
    },
    {
      id: 'instalacje-tynki-wylewki',
      name: 'Instalacje, tynki, wylewki',
      description: 'Kontrola wykonania wszystkich instalacji wewnętrznych, tynków i wylewek',
      items: [
        'Sprawdź projekt instalacji elektrycznej (uprawnienia projektanta)',
        'Zweryfikuj przekroje przewodów (NYM 3×2,5 dla gniazdek)',
        'Sprawdź obwody rozdzielnicze (ilość, zabezpieczenia)',
        'Zweryfikuj rozdzielnicę elektryczną (typ, ochrona, RCD)',
        'Sprawdź montaż puszek elektrycznych (głębokość, poziom)',
        'Zweryfikuj trasy kablowe (brak krzyżowania naprężonych kabli)',
        'Sprawdź uziemienie i ochronę przepięciową',
        'Zweryfikuj protokół z pomiaru instalacji elektrycznej',
        'Sprawdź projekt instalacji wod-kan (uprawnienia)',
        'Zweryfikuj materiał rur (PP, PEX, miedź)',
        'Sprawdź próbę ciśnieniową instalacji wodnej (6 bar przez 1h)',
        'Zweryfikuj spadki kanalizacji (min 2% dla DN 110)',
        'Sprawdź odpowietrzenie pionu kanalizacyjnego',
        'Zweryfikuj rewizje i czyszczaki na kanalizacji',
        'Sprawdź projekt instalacji grzewczej CO',
        'Zweryfikuj materiał rur grzewczych (PEX, wielowarstwowa)',
        'Sprawdź próbę ciśnieniową CO (6 bar przez 1h)',
        'Zweryfikuj rozdzielacze ogrzewania podłogowego (strefowanie)',
        'Sprawdź głębokość frezów pod rury (min 2 cm otuliny)',
        'Zweryfikuj projekt wentylacji mechanicznej (HRV/ERV)',
        'Sprawdź centrale wentylacyjną (rekuperacja min 80%)',
        'Zweryfikuj trasy kanałów wentylacyjnych (ocynk, flex)',
        'Sprawdź szczelność kanałów wentylacyjnych',
        'Zweryfikuj anemostaty i kratki wentylacyjne',
        'Sprawdź instalację gazową (próba szczelności)',
        'Zweryfikuj protokół odbioru gazu (gazownia)',
        'Sprawdź tynk wewnętrzny (gipsowy lub cementowo-wapienny)',
        'Zweryfikuj przygotowanie podłoża przed tynkowaniem',
        'Sprawdź grubość tynku (min 1 cm gipsowego)',
        'Zweryfikuj prostoliniowość tynku (łata 2m, odchyłka max 3mm)',
        'Sprawdź brak rys skurczowych i pęknięć tynku',
        'Zweryfikuj kąty i narożniki (profile aluminiowe)',
        'Sprawdź tynk zewnętrzny / elewacyjny (siatka zbrojąca)',
        'Zweryfikuj głębokość zatopienia siatki w tynku (min 2mm)',
        'Sprawdź podkład tynkarski na elewacji',
        'Zweryfikuj wylewkę cementową lub anhydrytową',
        'Sprawdź grubość wylewki (min 4,5 cm na COG, 6,5 cm na styro)',
        'Zweryfikuj poziom wylewki (łata 2m, odchyłka max 3mm)',
        'Sprawdź zbrojenie wylewki (siatka lub fiber)',
        'Zweryfikuj dylatacje wylewki (przy ścianach, co max 30m²)',
        'Sprawdź pielęgnację wylewki cementowej',
        'Zweryfikuj wilgotność wylewki przed układaniem podłogi',
        'Sprawdź wylewkę podgrzewana COG (próba grzejna)',
        'Zweryfikuj projekt elektryczny tablicy rozdzielczej',
        'Sprawdź UPS i zabezpieczenia przepięciowe',
        'Zweryfikuj instalację alarmową i domofon',
        'Sprawdź instalację sieciową i TV (Cat6, RG-6)',
        'Zweryfikuj instalację oświetlenia tarasów i zewnętrzna',
        'Sprawdź czy wszystkie inst. posiadają protokoły odbioru',
        'Zweryfikuj wpis kierownika do dziennika budowy',
        'Sprawdź zakrycia instalacji przed wylaniem wylewki (dokumentacja foto)',
        'Zweryfikuj zgodność z projektem (brak samowoli)',
        'Sprawdź czy materiały posiadają atesty i certyfikaty',
        'Zweryfikuj końcowy protokół odbioru wszystkich instalacji',
        'Sprawdź próbę ogrzewania (nagrzewanie całego systemu)',
        'Zweryfikuj zbilansowanie hydrauliczne ogrzewania',
        'Sprawdź sprawność pompy ciepła lub kotła',
        'Zweryfikuj regulację zaworu trójdrogowego',
        'Sprawdź bufory ciepła i zasobniki CWU',
        'Zweryfikuj instalację fotowoltaiczną (jeśli jest)',
        'Sprawdź falownik PV (certyfikat, parametry)',
        'Zweryfikuj izolację termiczną przewodów grzewczych',
        'Sprawdź izolację akustyczną pod wylewką',
        'Zweryfikuj projekt elektryczny podpisany przez kierownika',
        'Sprawdź certyfikaty materiałów izolacyjnych',
        'Zweryfikuj zgodność z normami PN-EN',
        'Sprawdź przejścia pożarowe przez ściany i stropy',
        'Zweryfikuj uszczelnienia ognioochronne (typ EI60+)',
        'Sprawdź wymiarowanie przekrojów kanałów wentylacji',
        'Zweryfikuj próbę rurociągów sprężonym powietrzem',
        'Sprawdź zasuwy i zawory na instalacji (typ, wymagania)',
        'Zweryfikuj prawidłowość oznaczeń elementów instalacji',
      ],
    },
    {
      id: 'termoizolacja-poddasza',
      name: 'Termoizolacja poddasza',
      description: 'Kontrola wykonania izolacji termicznej i paroizolacji poddasza',
      items: [
        'Sprawdź projekt izolacji (grubość wełny, wg WT2021)',
        'Zweryfikuj materiał izolacyjny (wełna mineralna λ ≤ 0,035)',
        'Sprawdź pierwszy layer wełny między krokwiami (szczelne wypełnienie)',
        'Zweryfikuj drugi layer wełny pod krokwiami (prostopadle)',
        'Sprawdź grubość łączną izolacji (min 30 cm dla WT2021)',
        'Zweryfikuj szczelność złączeń warstw wełny (bez mostków)',
        'Sprawdź folie paroizolacyjna (klasa Sd ≥ 5m)',
        'Zweryfikuj zakłady folii paroizolacyjnej (min 15cm, taśmowane)',
        'Sprawdź połączenie folii ze ścianami (taśma butylowa)',
        'Zweryfikuj brak uszkodzeń i dziur w folii',
        'Sprawdź szczelinę wentylacyjną za FWK (min 2cm)',
        'Zweryfikuj drożność kanałów wentylacyjnych pod dachem',
        'Sprawdź izolację okien dachowych (mansardowanie)',
      ],
    },
    {
      id: 'elewacja',
      name: 'Elewacja',
      description: 'Kontrola wykonania ocieplenia i tynku elewacyjnego metodą ETICS',
      items: [
        'Sprawdź projekt ocieplenia (grubość styropianu, typ)',
        'Zweryfikuj gatunek styropianu (EPS100 λ≤0,033 lub EPS150 cokół)',
        'Sprawdź przygotowanie podłoża (myjka, grunt)',
        'Zweryfikuj listwy startowe (poziom, mocowanie)',
        'Sprawdź klej do styropianu (aplikacja metodą obwodowo-punktową)',
        'Zweryfikuj przyklejenie płyt (min 40% powierzchni)',
        'Sprawdź układ płyt styropianu (mijankowy, odskok na narożnikach)',
        'Zweryfikuj kołkowanie styropianu (długość, ilość min 6 szt/m²)',
        'Sprawdź siatka zbrojąca (gramatura min 145 g/m²)',
        'Zweryfikuj głębokość zatopienia siatki w masie klejowej',
        'Sprawdź zakłady siatki na narożnikach (ukośne wstawki)',
        'Zweryfikuj czas sezonowania podkładu (min 72h)',
        'Sprawdź podkład tynkarski (kolor zbliżony do tynku)',
        'Zweryfikuj tynk elewacyjny (typ: silikonowy, mineralny)',
        'Sprawdź grubość tynku (zgodność z uziarnieniem)',
        'Zweryfikuj jednolitość faktury tynku (bez smug, odcieni)',
        'Sprawdź obróbki blacharskie (parapety, nakrywy)',
        'Zweryfikuj uszczelnienie połączeń elewacji z stolarką',
      ],
    },
  ],
  en: [
    {
      id: 'poszukiwanie-dzialki',
      name: 'Land Search and Purchase',
      description: 'Key steps during the selection and purchase of a safe construction plot',
      items: [
        'Analysis of Local Spatial Development Plan (MPZP) or Zoning Approval (WZ)',
        'Verification of the land and mortgage register (no encumbrances, mortgages, easements)',
        'Verification of public road access (direct or road easement)',
        'Geotechnical soil testing (load-bearing capacity, groundwater level)',
        'Verification of existing utilities (water, electricity, gas, sewage in the road)',
        'Verification of land topography (slopes, flood risk, shape)',
        'Assessment of surroundings and nuisances (noise, proximity to industrial zones, distance from forest/river)',
        'Check of land records (agricultural land class, e.g., RIII, RIV)',
        'Verification of overhead and underground power lines (protective zones)',
        'Measurements and boundary staking by an authorized surveyor',
        'Price negotiations and signing a preliminary agreement',
        'Signing the notarized purchase deed',
        'Payment of Transfer Tax (PCC) at the notary',
      ],
    },
    {
      id: 'administracja-formalnosci',
      name: 'Administration and Formalities',
      description: 'Paperwork stage from plot purchase to building permit',
      items: [
        'Submission of application for Zoning Approval (WZ) – if no MPZP',
        'Application for electricity connection conditions (PGE/Tauron/etc.)',
        'Application for water and sewage connection conditions',
        'Application for gas connection conditions (optional)',
        'Selection and purchase of a ready-made project or commissioning an individual project',
        'Adaptation of the ready-made project to plot conditions by an adapting architect',
        'Plot development project (PZT)',
        'Geological soil testing – including the opinion in the building project (if required)',
        'Exclusion of land from agricultural/forest production in the starosty',
        'Agreement for entry/exit from the road with the road manager (e.g., ZDW)',
        'Submission of application for Building Permit or building notification (with all attachments)',
        'Wait for the building permit decision to become final (usually 14 days)',
        'Download and stamp the Building Logbook from the office',
        'Notification of commencement of construction works to PINB, at least 7 days before starting',
        'Hiring a Site Manager and submitting their statement on undertaking duties',
      ],
    },
    {
      id: 'przygotowanie-budowy',
      name: 'Site Preparation',
      description: 'Physical preparation work before digging the first spade',
      items: [
        'Designation of danger zones and traffic organization on the construction site',
        'Installation of temporary fencing for the construction site',
        'Hanging the yellow information board in a visible place',
        'Setting up sanitary facilities (portable toilet) for the construction crew',
        'Ensuring access to water (hydrant, dug well, or water tank)',
        'Execution of temporary electricity connection (RB-tka construction box)',
        'Setting up a secure shed/container for small tools and cement',
        'Preparation of access road for heavy equipment (hauling and compacting aggregate or road plates)',
        'Grubbing of shrubs and tree clearing (if required and consent obtained)',
        'Removal and storage of the top layer of plant soil (humus) on a deposit heap',
        'Surveying layout of the building body on wire batter boards by an authorized surveyor',
        'Organization of a storage area for reinforcing steel and mass materials on pads',
        'Arrival of the crew responsible for foundation works',
      ],
    },
    {
      id: 'fundamenty-tradycyjne',
      name: 'Traditional Foundations',
      description: 'Complete quality control of foundations in traditional technology (concrete pour or blocks)',
      items: [
        'Check surveying layout of plot and building',
        'Verify terrain levels according to the project',
        'Check excavation dimensions (width, depth)',
        'Verify foundation level (leveler/staff)',
        'Check leveling of excavation floor',
        'Verify soil under foundation (load capacity, no water)',
        'Check if humus layer has been removed',
        'Verify gravel or sand bedding (thickness)',
        'Check reinforcement of foundation footings (diameters, spacing, cover thickness)',
        'Verify continuity of stirrups in footings',
        'Check reinforcement doweling at corners',
        'Verify reinforcement starters for walls',
        'Check concrete quality (class according to project)',
        'Verify concrete consistency during delivery',
        'Check concrete pouring (no aggregate segregation)',
        'Verify concrete vibration',
        'Check if foundation footing surface leveling is maintained',
        'Verify concrete curing (moisturization)',
        'Check level of poured footings (max deviation 2cm)',
        'Verify mutual connection of footings at corners',
        'Check damp-proof insulation of footings (torch-on felt or bituminous mass)',
        'Verify continuity of horizontal insulation',
        'Check vertical insulation of foundation walls',
        'Verify quality of concrete blocks (dimensions, class)',
        'Check thickness of mortar between blocks',
        'Verify block bonding at corners (offset)',
        'Check plumbness and level of block walls',
        'Verify tightness of joints',
        'Check if blocks are not broken or damaged',
        'Verify openings in the wall (installation sleeves)',
        'Check level of the reinforced concrete beam',
        'Verify beam reinforcement (load capacity, cover thickness)',
        'Check connection of the beam with the foundation footing',
        'Verify beam concrete pour',
        'Check thermal insulation of foundation (XPS, Styrodur)',
        'Verify thickness of thermal insulation layer',
        'Check perimeter or French drainage',
        'Verify drain tightness',
        'Check ground level at foundation (drip edge)',
        'Verify water drainage from embankment slope',
        'Check concrete floor base (thickness)',
        'Verify leveling of the base',
        'Check vapor barrier film under the floor',
        'Verify continuity of the film (overlaps, sealings)',
        'Check floor thermal insulation (styrofoam, XPS)',
        'Verify thickness of floor thermal insulation',
        'Check installation outlets (water-sewage, heating)',
        'Verify excavation backfill (aggregate, staged compaction)',
        'Check soil compaction with a compactor',
        'Verify ground level after backfilling',
        'Check for lack of cracks and defects in foundations before burial',
        'Verify as-built documentation for foundations',
        'Check foundation works acceptance report',
        'Verify entry in the building logbook by the manager',
      ],
    },
    {
      id: 'plyta-fundamentowa',
      name: 'Foundation Slab',
      description: 'Quality control of foundation slab execution (monolithic technology)',
      items: [
        'Check surveying layout of the slab',
        'Verify dimensions and shape of the slab according to project',
        'Check foundation depth',
        'Verify removal of humus layer',
        'Check soil under the slab (load capacity, no organic matter)',
        'Verify bedding (stabilized aggregate, min. 15cm thickness)',
        'Check bedding compaction',
        'Verify thermal insulation under the slab (XPS, min. 15cm)',
        'Check layout of vapor barrier film (20cm overlaps, taping)',
        'Verify perimeter formwork of the slab (straightness)',
        'Check lower reinforcement of the slab (mesh, spacing, min 3cm cover)',
        'Verify upper reinforcement of the slab',
        'Check spacer pads under reinforcement (concrete, not plastic)',
        'Verify reinforcement starters for walls',
        'Check installation sleeves (water-sewage, central heating, electricity)',
        'Verify concrete heating (in winter conditions)',
        'Check concrete consistency during delivery (slump test)',
        'Verify concrete class (at least C20/25 according to project)',
        'Check pouring stages and concrete vibration',
        'Verify surface leveling and floating',
        'Check concrete curing (with film or mat)',
        'Verify level of the finished slab (max 5mm/2m deviation)',
        'Check for lack of cracks and fissures after hardening',
        'Verify lack of voids and cavities in concrete',
        'Check perimeter thermal insulation (XPS plinth)',
        'Verify continuity of perimeter insulation',
        'Check sealing of installation penetrations',
        'Verify foundation slab acceptance report',
        'Check photographic documentation of reinforcement before concreting',
        'Verify entry in the building logbook',
      ],
    },
    {
      id: 'stan-surowy-otwarty',
      name: 'Open Shell State',
      description: 'Comprehensive quality control of the building in the open shell state (walls, slabs, roof)',
      items: [
        'Check building axis and floor plan dimensions (surveyor)',
        'Verify verticality of exterior walls (max deviation 1cm/m)',
        'Check level of the first wall layer',
        'Verify joint thickness between blocks/bricks',
        'Check block bonding at corners',
        'Verify correctness of window openings (dimensions, frames)',
        'Check correctness of door openings',
        'Verify lintels over openings (type, load capacity)',
        'Check reinforcement of concrete lintels',
        'Verify filling of prefabricated lintels',
        'Check reinforced concrete beam at slab level (reinforcement)',
        'Verify beam concrete (class, continuity)',
        'Check connection of the beam with walls',
        'Verify reinforcement of columns and pillars',
        'Check thickness of load-bearing walls (project compliance)',
        'Verify thickness of partition walls',
        'Check material of partition walls (silicate bricks, blocks)',
        'Verify connection of partition walls with load-bearing walls',
        'Check cavity wall filling',
        'Verify acoustic insulation between walls',
        'Check monolithic reinforced concrete slab (lower and upper reinforcement)',
        'Verify slab formwork (tightness, level)',
        'Check formwork support (support spacing)',
        'Verify slab concrete (class, vibration)',
        'Check slab thickness (according to project)',
        'Verify prefabricated slab (Teriva/Filigran – directional assembly)',
        'Check topping on prefabricated slab',
        'Verify openings in the slab (stairs, installations)',
        'Check level of finished slab (max deviation 1cm)',
        'Verify lack of cracks and fissures in the slab',
        'Check wooden floor beams (C24 class, section according to project)',
        'Verify wooden beam spacing',
        'Check beam anchoring in the wall plate/beam',
        'Verify wood impregnation (fire-retardant, anti-fungal)',
        'Check wall plate (wood species, connections)',
        'Verify anchoring of the wall plate to the beam (M16 anchors)',
        'Check rafters (section, spacing, notches)',
        'Verify ridge and purlins',
        'Check columns and braces of the roof structure',
        'Verify metal connectors of the structure (mauerlat, angle brackets)',
        'Check verticality of structure columns',
        'Verify roof symmetry (diagonal measurements)',
        'Check inclination angle of roof planes (project compliance)',
        'Verify battens and counter-battens (dimensions, spacing)',
        'Check initial roofing film (FWK), class W1 or W3',
        'Verify FWK installation (overlaps, taping)',
        'Check roofing material (tiles, metal tiles)',
        'Verify ridge sealing',
        'Check fixing of metal flashings (gutters, eaves strips)',
        'Verify water drainage from the roof (downpipes)',
        'Check roof windows / skylights (installation, tightness)',
        'Verify chimneys (dimensions, verticality, heads)',
        'Check sealing of chimney roof penetration',
        'Verify roof hatch (access, hardware)',
        'Check internal or external stairs',
        'Verify floor level on each floor',
        'Check lack of cracks in walls after heavy rains',
        'Verify terrain drainage near the building',
        'Check lack of water ponding near foundations',
        'Verify protection of the building against vandalism (temporary windows/doors)',
        'Check correctness of as-built surveying inventory',
        'Verify compliance with building project and zoning conditions',
        'Check building logbook – entries by manager and inspector',
        'Verify masonry works acceptance report',
        'Check slab acceptance report',
        'Verify roof structure acceptance report',
        'Check roofing acceptance report',
        'Verify photographic documentation of individual stages',
        'Check if building is within the plan area or WZ',
        'Verify compliance with building permit',
        'Check if building lines are not exceeded',
        'Verify distances from plot boundaries',
        'Check auxiliary project (e.g., roof structure calculations)',
        'Verify if site manager is up to date with the logbook',
        'Check if materials have declarations of performance',
        'Verify certificates of building products',
        'Check lack of mechanical damage to structural elements',
        'Verify cleanliness and order on the construction site',
        'Check construction site organization (fencing, board)',
        'Verify occupational safety and health conditions on site',
        'Check protection of openings (screens, temporary railings)',
        'Verify marking of dangerous zones',
        'Check technical condition of scaffoldings',
        'Verify scaffolding certificates',
        'Check lightning rod on site (if required)',
        'Verify electric energy meter on site',
        'Check water intake on site',
        'Verify sanitary facilities for workers',
        'Check building materials storage site',
        'Verify construction waste container',
      ],
    },
    {
      id: 'okna-drzwi',
      name: 'Windows and Doors',
      description: 'Quality control of window and door joinery installation and quality',
      items: [
        'Check window dimensions according to project',
        'Verify window U-value (acc. to documentation, max 0.9 W/m²K)',
        'Check frame profile (thickness, chambers, class)',
        'Verify glazing type (triple-glazed recommended)',
        'Check verticality and horizontality of the frame',
        'Verify installation on system connectors (not just foam)',
        'Check vapor-permeable tape installation on the outside',
        'Verify vapor-barrier tape installation on the inside',
        'Check joint filling with low-expansion foam',
        'Verify external window sill level (water runoff)',
        'Check internal window sill (fixing, sealing)',
        'Verify operation of sashes (opening, closing, tilting)',
        'Check entrance doors (class, RC2 recommended)',
      ],
    },
    {
      id: 'instalacje-tynki-wylewki',
      name: 'Installations, Plasters, Screeds',
      description: 'Quality control of all internal installations, plasters, and screeds',
      items: [
        'Check electrical installation project (designer qualifications)',
        'Verify wire sections (NYM 3×2.5 for sockets)',
        'Check distributional circuits (quantity, protections)',
        'Verify electrical distribution board (type, protection, RCD)',
        'Check installation of electrical boxes (depth, level)',
        'Verify cable routes (no crossing of stretched cables)',
        'Check grounding and surge protection',
        'Verify electrical installation measurement report',
        'Check water-sewage installation project (qualifications)',
        'Verify pipe material (PP, PEX, copper)',
        'Check water system pressure test (6 bar for 1h)',
        'Verify sewage slopes (min 2% for DN 110)',
        'Check sewage stack venting',
        'Verify inspections and cleanouts on sewage system',
        'Check central heating (CO) installation project',
        'Verify heating pipe material (PEX, multilayer)',
        'Check CO system pressure test (6 bar for 1h)',
        'Verify underfloor heating manifolds (zoning)',
        'Check depth of grooves for pipes (min 2 cm cover)',
        'Verify mechanical ventilation project (HRV/ERV)',
        'Check ventilation unit (recovery min 80%)',
        'Verify ventilation duct routes (galvanized, flex)',
        'Check ventilation duct tightness',
        'Verify anemostats and ventilation grilles',
        'Check gas installation (leak test)',
        'Verify gas acceptance report (gas company)',
        'Check internal plaster (gypsum or cement-lime)',
        'Verify substrate preparation before plastering',
        'Check plaster thickness (min 1 cm for gypsum)',
        'Verify plaster straightness (2m staff, max 3mm deviation)',
        'Check for lack of shrinkage cracks and plaster fissures',
        'Verify angles and corners (aluminum profiles)',
        'Check external / facade plaster (reinforcing mesh)',
        'Verify embedding depth of mesh in plaster (min 2mm)',
        'Check plaster base on the facade',
        'Verify cement or anhydrite screed',
        'Check screed thickness (min 4.5 cm for underfloor heating, 6.5 cm on styro)',
        'Verify screed level (2m staff, max 3mm deviation)',
        'Check screed reinforcement (mesh or fiber)',
        'Verify screed expansion joints (at walls, max 30m²)',
        'Check cement screed curing',
        'Verify screed humidity before floor laying',
        'Check heated floor screed (heating test)',
        'Verify electrical project of distribution board',
        'Check UPS and surge protection',
        'Verify alarm installation and intercom',
        'Check network and TV installation (Cat6, RG-6)',
        'Verify terrace and external lighting installation',
        'Check if all installations have acceptance reports',
        'Verify site manager\'s entry in the logbook',
        'Check installation coverage before screed pour (photo documentation)',
        'Verify compliance with the project',
        'Check if materials have approvals and certificates',
        'Verify final acceptance report of all installations',
        'Check heating test (warming up the whole system)',
        'Verify hydraulic balancing of the heating system',
        'Check efficiency of heat pump or boiler',
        'Verify 3-way valve adjustment',
        'Check thermal buffers and DHW tanks',
        'Verify photovoltaic installation (if present)',
        'Check PV inverter (certificate, parameters)',
        'Verify thermal insulation of heating pipes',
        'Check acoustic insulation under the screed',
        'Verify electrical project signed by the manager',
        'Check certificates of insulation materials',
        'Verify compliance with PN-EN standards',
        'Check fire penetrations through walls and slabs',
        'Verify fire-stop seals (EI60+ type)',
        'Check dimensioning of ventilation duct sections',
        'Verify pipe system test with compressed air',
        'Check gates and valves on the installation (type, requirements)',
        'Verify correctness of installation element markings',
      ],
    },
    {
      id: 'termoizolacja-poddasza',
      name: 'Attic Thermal Insulation',
      description: 'Quality control of attic thermal insulation and vapor barrier execution',
      items: [
        'Check insulation project (wool thickness, acc. to WT2021)',
        'Verify insulation material (mineral wool λ ≤ 0.035)',
        'Check first layer of wool between rafters (tight filling)',
        'Verify second layer of wool under rafters (perpendicular)',
        'Check total insulation thickness (min 30 cm for WT2021)',
        'Verify tightness of wool layer joins (no bridges)',
        'Check vapor barrier film (class Sd ≥ 5m)',
        'Verify overlaps of vapor barrier film (min 15cm, taped)',
        'Check connection of the film with walls (butyl tape)',
        'Verify lack of damage and holes in the film',
        'Check ventilation gap behind FWK (min 2cm)',
        'Verify clearance of ventilation channels under the roof',
        'Check roof window insulation (mansard work)',
      ],
    },
    {
      id: 'elewacja',
      name: 'Facade',
      description: 'Quality control of facade insulation and plaster execution using ETICS method',
      items: [
        'Check insulation project (styrofoam thickness, type)',
        'Verify styrofoam grade (EPS100 λ≤0.033 or EPS150 plinth)',
        'Check substrate preparation (washer, primer)',
        'Verify starter strips (level, fixing)',
        'Check styrofoam adhesive (perimeter-point application)',
        'Verify board adhesion (min 40% area)',
        'Check styrofoam board layout (offset, corner overlap)',
        'Verify styrofoam doweling (length, quantity min 6 pcs/m²)',
        'Check reinforcing mesh (weight min 145 g/m²)',
        'Verify embedding depth of mesh in adhesive mass',
        'Check mesh overlaps at corners (diagonal inserts)',
        'Verify curing time of the base (min 72h)',
        'Check plaster primer (color close to plaster)',
        'Verify facade plaster (type: silicone, mineral)',
        'Check plaster thickness (acc. to grain size)',
        'Verify uniformity of plaster texture (no streaks, shades)',
        'Check metal flashings (window sills, covers)',
        'Verify sealing of facade connections with joinery',
      ],
    },
  ],
}
