export interface ChecklistTemplate {
  id: string
  name: string
  description: string
  items: string[]
}

export const CHECKLIST_TEMPLATES: ChecklistTemplate[] = [
  {
    id: 'fundamenty-tradycyjne',
    name: 'Fundamenty tradycyjne',
    description: 'Kompletna kontrola jakości fundamentów w technologii tradycyjnej (wylew betonowy lub bloczki)',
    items: [
      'Sprawdź wytyczenie geodezyjne działki i budynku',
      'Zweryfikuj rzędne terenu zgodnie z projektem',
      'Sprawdź wymiary wykopu (szerokość, głębokość)',
      'Zweryfikuj poziom posadowienia (niwelator/łata)',
      'Sprawdź wyrównanie dna wykopu',
      'Zweryfikuj grunt pod fundamentem (nośność, brak nawodnień)',
      'Sprawdź czy usunięto warstwę humusu',
      'Zweryfikuj podsypkę żwirową lub piaskową (grubość)',
      'Sprawdź zbrojenie ław fundamentowych (średnice, rozstaw, grubość otuliny)',
      'Zweryfikuj ciągłość strzemion w ławach',
      'Sprawdź dyblowanie zbrojenia na narożnikach',
      'Zweryfikuj wypusty zbrojeniowe pod ściany',
      'Sprawdź jakość betonu (klasa wg projektu)',
      'Zweryfikuj konsystencję betonu przy dostawie',
      'Sprawdź wylewanie betonu (brak segregacji kruszywa)',
      'Zweryfikuj wibrowanie betonu',
      'Sprawdź czy zachowane wyrównanie powierzchni ław',
      'Zweryfikuj pielęgnację betonu (nawilżanie)',
      'Sprawdź poziom wylanych ław (odchyłka max 2cm)',
      'Zweryfikuj wzajemne powiązanie ław w narożnikach',
      'Sprawdź izolację przeciwwilgociową ław (papa termozgrzewalna lub masa bitumiczna)',
      'Zweryfikuj ciągłość izolacji poziomej',
      'Sprawdź izolację pionową ścian fundamentowych',
      'Zweryfikuj jakość bloczków betonowych (wymiary, klasa)',
      'Sprawdź grubość zaprawy między bloczkami',
      'Zweryfikuj powiązanie bloczków na narożnikach (mijankowe)',
      'Sprawdź pionie i poziome ścian z bloczków',
      'Zweryfikuj szczelność spoin',
      'Sprawdź czy bloczki nie są rozbite lub uszkodzone',
      'Zweryfikuj otworowania w murze (przepusty instalacyjne)',
      'Sprawdź poziom wieńca żelbetowego',
      'Zweryfikuj zbrojenie wieńca (nośność, grubość otuliny)',
      'Sprawdź połączenie wieńca z ławą fundamentową',
      'Zweryfikuj wylew betonu wieńca',
      'Sprawdź izolację termiczną fundamentu (XPS, Styrodur)',
      'Zweryfikuj grubość warstwy izolacji termicznej',
      'Sprawdź drenaż opaskowy lub francuski',
      'Zweryfikuj szczelność drenażu',
      'Sprawdź poziom terenu przy fundamencie (odskok wodny)',
      'Zweryfikuj odprowadzenie wody ze wzgórza skarpy',
      'Sprawdź podkład betonowy pod posadzkę (grubość)',
      'Zweryfikuj wyrównanie podkładu',
      'Sprawdź folię paroizolacyjną pod posadzką',
      'Zweryfikuj ciągłość folii (zakłady, uszczelnienia)',
      'Sprawdź izolację termiczną podposadzkową (styropian, XPS)',
      'Zweryfikuj grubość izolacji termicznej podposadzkowej',
      'Sprawdź wypusty instalacyjne (wod-kan, ogrzewanie)',
      'Zweryfikuj obsypkę wykopu (kruszywo, etapowe zagęszczanie)',
      'Sprawdź zagęszczenie gruntu zagęszczarką',
      'Zweryfikuj poziom terenu po obsypce',
      'Sprawdź brak pęknięć i ubytków w fundamentach przed zasypaniem',
      'Zweryfikuj dokumentację powykonawczą fundamentów',
      'Sprawdź protokół odbioru robót fundamentowych',
      'Zweryfikuj wpis do dziennika budowy przez kierownika',
    ],
  },
  {
    id: 'plyta-fundamentowa',
    name: 'Płyta fundamentowa',
    description: 'Kontrola jakości wykonania płyty fundamentowej (technologia monolityczna)',
    items: [
      'Sprawdź wytyczenie geodezyjne płyty',
      'Zweryfikuj wymiary i kształt płyty zgodnie z projektem',
      'Sprawdź głębokość posadowienia',
      'Zweryfikuj usunięcie warstwy humusu',
      'Sprawdź grunt pod płytą (nośność, brak organiki)',
      'Zweryfikuj podsypkę (kruszywo stabilizowane, grubość min. 15cm)',
      'Sprawdź zagęszczenie podsypki',
      'Zweryfikuj izolację termiczną pod płytą (XPS, min. 15cm)',
      'Sprawdź ułożenie folii paroizolacyjnej (zakłady 20cm, taśmowanie)',
      'Zweryfikuj szalunek obwodowy płyty (prostoliniowość)',
      'Sprawdź zbrojenie dolne płyty (siatka, rozstaw, otulina min 3cm)',
      'Zweryfikuj zbrojenie górne płyty',
      'Sprawdź podkładki dystansowe pod zbrojeniem (beton, nie plastik)',
      'Zweryfikuj wypusty zbrojeniowe pod ściany',
      'Sprawdź przepusty instalacyjne (wod-kan, CO, prąd)',
      'Zweryfikuj zagrzewanie betonu (w warunkach zimowych)',
      'Sprawdź konsystencję betonu przy dostawie (slump test)',
      'Zweryfikuj klasę betonu (co najmniej C20/25 wg projektu)',
      'Sprawdź etapy wylewania i wibrowanie betonu',
      'Zweryfikuj wyrównanie i zatarcie powierzchni',
      'Sprawdź pielęgnację betonu (folią lub mata)',
      'Zweryfikuj poziom ukończonej płyty (odchyłka max 5mm/2m)',
      'Sprawdź brak rys i pęknięć po stwardnieniu',
      'Zweryfikuj brak pustek i kawern w betonie',
      'Sprawdź izolację termiczną obwodową (cokół XPS)',
      'Zweryfikuj ciągłość izolacji obwodowej',
      'Sprawdź uszczelnienie przejść instalacyjnych',
      'Zweryfikuj protokół odbioru płyty fundamentowej',
      'Sprawdź dokumentację fotograficzną zbrojenia przed betonowaniem',
      'Zweryfikuj wpis do dziennika budowy',
    ],
  },
  {
    id: 'stan-surowy-otwarty',
    name: 'Stan surowy otwarty',
    description: 'Kompleksowa kontrola jakości budynku w stanie surowym otwartym (ściany, stropy, dach)',
    items: [
      'Sprawdź oś budynku i wymiary rzutu (geodeta)',
      'Zweryfikuj pionowość ścian zewnętrznych (odchyłka max 1cm/m)',
      'Sprawdź poziom pierwszej warstwy ścian',
      'Zweryfikuj grubość spoin między bloczkami/cegłą',
      'Sprawdź powiązanie bloczków na narożnikach',
      'Zweryfikuj prawidłowość otworu na okna (wymiary, ościeżnice)',
      'Sprawdź prawidłowość otworów drzwiowych',
      'Zweryfikuj nadproża nad otworami (rodzaj, nośność)',
      'Sprawdź zbrojenie nadproży betonowych',
      'Zweryfikuj wypełnienie nadproży prefabrykowanych',
      'Sprawdź wieniec żelbetowy na poziomie stropu (zbrojenie)',
      'Zweryfikuj beton wieńca (klasa, ciągłość)',
      'Sprawdź połączenie wieńca ze ścianami',
      'Zweryfikuj zbrojenie słupów i trzpieni',
      'Sprawdź grubość ścian nośnych (zgodność z projektem)',
      'Zweryfikuj grubość ścian działowych',
      'Sprawdź materiał ścian działowych (cegła silikatowa, bloczki)',
      'Zweryfikuj powiązanie ścian działowych z nośnymi',
      'Sprawdź wypełnienie ścian szczelinowych',
      'Zweryfikuj izolację akustyczną między ścianami',
      'Sprawdź strop żelbetowy monolityczny (zbrojenie dołem i górą)',
      'Zweryfikuj szalunek stropu (szczelność, poziom)',
      'Sprawdź podparcie szalunku (rozstaw podpór)',
      'Zweryfikuj beton stropu (klasa, wibrowanie)',
      'Sprawdź grubość płyty stropowej (wg projektu)',
      'Zweryfikuj strop prefabrykowany (Teriva/Filigran – montaż kierunkowy)',
      'Sprawdź nadbeton na stropie prefabrykowanym',
      'Zweryfikuj otwory w stropie (schody, instalacje)',
      'Sprawdź poziom gotowego stropu (odchyłka max 1cm)',
      'Zweryfikuj brak rys i pęknięć w stropie',
      'Sprawdź belki stropowe drewniane (klasa C24, przekrój wg projektu)',
      'Zweryfikuj rozstaw belek drewnianych',
      'Sprawdź zakotwienie belek w wieńcu',
      'Zweryfikuj impregnację drewna (ognioochronna, grzybochronna)',
      'Sprawdź murłatę (gatunek drewna, połączenia)',
      'Zweryfikuj zakotwienie murłaty do wieńca (kotwy M16)',
      'Sprawdź krokwie (przekrój, rozstaw, nacięcia)',
      'Zweryfikuj kalenicę i płatwie',
      'Sprawdź słupy i miecze więźby dachowej',
      'Zweryfikuj metalowe łączniki więźby (mauerlat, kątowniki)',
      'Sprawdź pionowość słupów więźby',
      'Zweryfikuj symetrię dachu (pomiary przekątnych)',
      'Sprawdź kąt nachylenia połaci (zgodność z projektem)',
      'Zweryfikuj łaty i kontrłaty (wymiary, rozstaw)',
      'Sprawdź folię wstępnego krycia (FWK), klasy W1 lub W3',
      'Zweryfikuj montaż FWK (zakłady, taśmowanie)',
      'Sprawdź pokrycie dachowe (dachówka, blachodachówka)',
      'Zweryfikuj uszczelnienie kalenicowania',
      'Sprawdź mocowanie obróbek blacharskich (rynny, pasy nadrynnowe)',
      'Zweryfikuj odprowadzenie wody z dachu (rury spustowe)',
      'Sprawdź okna dachowe / świetliki (montaż, szczelność)',
      'Zweryfikuj kominy (wymiary, pionowość, głowice)',
      'Sprawdź uszczelnienie przejścia komina przez dach',
      'Zweryfikuj wyłaz dachowy (dostęp, okucia)',
      'Sprawdź schody wewnętrzne lub zewnętrzne',
      'Zweryfikuj poziom podłogi na każdym piętrze',
      'Sprawdź brak pęknięć w ścianach po ciężkich deszczach',
      'Zweryfikuj odwodnienie terenu przy budynku',
      'Sprawdź brak zastoiny wody przy fundamentach',
      'Zweryfikuj zabezpieczenie budynku przed dewastacją (okna, drzwi tymczasowe)',
      'Sprawdź prawidłowość inwentaryzacji geodezyjnej powykonawczej',
      'Zweryfikuj zgodność z projektem budowlanym i warunkami zabudowy',
      'Sprawdź dziennik budowy – wpisy kierownika i inspektora',
      'Zweryfikuj protokół odbioru robót murowych',
      'Sprawdź protokół odbioru stropu',
      'Zweryfikuj protokół odbioru więźby dachowej',
      'Sprawdź protokół odbioru pokrycia dachowego',
      'Zweryfikuj dokumentację fotograficzną poszczególnych etapów',
      'Sprawdź czy budynek jest zawarty w obszarze planu lub WZ',
      'Zweryfikuj zgodność z pozwoleniem na budowę',
      'Sprawdź czy nie przekroczono linii zabudowy',
      'Zweryfikuj odległości od granic działki',
      'Sprawdź projekt pomocniczy (np. obliczenia więźby)',
      'Zweryfikuj czy kierownik budowy jest na bieżąco z dziennikiem',
      'Sprawdź czy materiały posiadają deklaracje właściwości użytkowych',
      'Zweryfikuj certyfikaty wyrobów budowlanych',
      'Sprawdź brak uszkodzeń mechanicznych elementów konstrukcyjnych',
      'Zweryfikuj czystość i porządek na placu budowy',
      'Sprawdź organizację placu budowy (ogrodzenie, tablica)',
      'Zweryfikuj warunki bhp na budowie',
      'Sprawdź zabezpieczenie otworów (ekrany, balustrady tymczasowe)',
      'Zweryfikuj oznakowanie stref niebezpiecznych',
      'Sprawdź stan techniczny rusztowań',
      'Zweryfikuj certyfikaty rusztowań',
      'Sprawdź piorunochron na budowie (jeśl wymagany)',
      'Zweryfikuj licznik energii elektrycznej na budowie',
      'Sprawdź ujęcie wody na budowie',
      'Zweryfikuj węzeł sanitarny dla pracowników',
      'Sprawdź składowisko materiałów budowlanych',
      'Zweryfikuj kontener na odpady budowlane',
    ],
  },
  {
    id: 'okna-drzwi',
    name: 'Okna i drzwi',
    description: 'Kontrola montażu i jakości stolarki okiennej i drzwiowej',
    items: [
      'Sprawdź wymiary okien zgodne z projektem',
      'Zweryfikuj współczynnik U okien (wg dokumentacji, max 0.9 W/m²K)',
      'Sprawdź profil ramy (grubość, komory, klasa)',
      'Zweryfikuj rodzaj szyby (trojszybowa zalecana)',
      'Sprawdź pionowość i poziomość ościeżnicy',
      'Zweryfikuj montaż na łącznikach systemowych (nie na piankę)',
      'Sprawdź montaż paroprzepuszczalnej taśmy od zewnątrz',
      'Zweryfikuj montaż paroizolacyjnej taśmy od wewnątrz',
      'Sprawdź wypełnienie szczelin pianką niskoprzężną',
      'Zweryfikuj poziom parapetu zewnętrznego (odpad wody)',
      'Sprawdź parapet wewnętrzny (mocowanie, uszczelnienie)',
      'Zweryfikuj działanie skrzydeł (otwieranie, zamykanie, uchylanie)',
      'Sprawdź drzwi wejściowe (klasa, RC2 zalecana)',
    ],
  },
  {
    id: 'instalacje-tynki-wylewki',
    name: 'Instalacje, tynki, wylewki',
    description: 'Kontrola wykonania wszystkich instalacji wewnętrznych, tynków i wylewek',
    items: [
      'Sprawdź projekt instalacji elektrycznej (uprawnienia projektanta)',
      'Zweryfikuj przekroje przewodów (NYM 3×2,5 dla gniazdek)',
      'Sprawdź obwody rozdzielnicze (ilość, zabezpieczenia)',
      'Zweryfikuj rozdzielnicę elektryczną (typ, ochrona, RCD)',
      'Sprawdź montaż puszek elektrycznych (głębokość, poziom)',
      'Zweryfikuj trasy kablowe (brak krzyżowania naprężonych kabli)',
      'Sprawdź uziemienie i ochronę przepięciową',
      'Zweryfikuj protokół z pomiaru instalacji elektrycznej',
      'Sprawdź projekt instalacji wod-kan (uprawnienia)',
      'Zweryfikuj materiał rur (PP, PEX, miedź)',
      'Sprawdź próbę ciśnieniową instalacji wodnej (6 bar przez 1h)',
      'Zweryfikuj spadki kanalizacji (min 2% dla DN 110)',
      'Sprawdź odpowietrzenie pionu kanalizacyjnego',
      'Zweryfikuj rewizje i czyszczaki na kanalizacji',
      'Sprawdź projekt instalacji grzewczej CO',
      'Zweryfikuj materiał rur grzewczych (PEX, wielowarstwowa)',
      'Sprawdź próbę ciśnieniową CO (6 bar przez 1h)',
      'Zweryfikuj rozdzielacze ogrzewania podłogowego (strefowanie)',
      'Sprawdź głębokość frezów pod rury (min 2 cm otuliny)',
      'Zweryfikuj projekt wentylacji mechanicznej (HRV/ERV)',
      'Sprawdź centrale wentylacyjną (rekuperacja min 80%)',
      'Zweryfikuj trasy kanałów wentylacyjnych (ocynk, flex)',
      'Sprawdź szczelność kanałów wentylacyjnych',
      'Zweryfikuj anemostaty i kratki wentylacyjne',
      'Sprawdź instalację gazową (próba szczelności)',
      'Zweryfikuj protokół odbioru gazu (gazownia)',
      'Sprawdź tynk wewnętrzny (gipsowy lub cementowo-wapienny)',
      'Zweryfikuj przygotowanie podłoża przed tynkowaniem',
      'Sprawdź grubość tynku (min 1 cm gipsowego)',
      'Zweryfikuj prostoliniowość tynku (łata 2m, odchyłka max 3mm)',
      'Sprawdź brak rys skurczowych i pęknięć tynku',
      'Zweryfikuj kąty i narożniki (profile aluminiowe)',
      'Sprawdź tynk zewnętrzny / elewacyjny (siatka zbrojąca)',
      'Zweryfikuj głębokość zatopienia siatki w tynku (min 2mm)',
      'Sprawdź podkład tynkarski na elewacji',
      'Zweryfikuj wylewkę cementową lub anhydrytową',
      'Sprawdź grubość wylewki (min 4,5 cm na COG, 6,5 cm na styro)',
      'Zweryfikuj poziom wylewki (łata 2m, odchyłka max 3mm)',
      'Sprawdź zbrojenie wylewki (siatka lub fiber)',
      'Zweryfikuj dylatacje wylewki (przy ścianach, co max 30m²)',
      'Sprawdź pielęgnację wylewki cementowej',
      'Zweryfikuj wilgotność wylewki przed układaniem podłogi',
      'Sprawdź wylewkę podgrzewana COG (próba grzejna)',
      'Zweryfikuj projekt elektryczny tablicy rozdzielczej',
      'Sprawdź UPS i zabezpieczenia przepięciowe',
      'Zweryfikuj instalację alarmową i domofon',
      'Sprawdź instalację sieciową i TV (Cat6, RG-6)',
      'Zweryfikuj instalację oświetlenia tarasów i zewnętrzna',
      'Sprawdź czy wszystkie inst. posiadają protokoły odbioru',
      'Zweryfikuj wpis kierownika do dziennika budowy',
      'Sprawdź zakrycia instalacji przed wylaniem wylewki (dokumentacja foto)',
      'Zweryfikuj zgodność z projektem (brak samowoli)',
      'Sprawdź czy materiały posiadają atesty i certyfikaty',
      'Zweryfikuj końcowy protokół odbioru wszystkich instalacji',
      'Sprawdź próbę ogrzewania (nagrzewanie całego systemu)',
      'Zweryfikuj zbilansowanie hydrauliczne ogrzewania',
      'Sprawdź sprawność pompy ciepła lub kotła',
      'Zweryfikuj regulację zaworu trójdrogowego',
      'Sprawdź bufory ciepła i zasobniki CWU',
      'Zweryfikuj instalację fotowoltaiczną (jeśli jest)',
      'Sprawdź falownik PV (certyfikat, parametry)',
      'Zweryfikuj izolację termiczną przewodów grzewczych',
      'Sprawdź izolację akustyczną pod wylewką',
      'Zweryfikuj projekt elektryczny podpisany przez kierownika',
      'Sprawdź certyfikaty materiałów izolacyjnych',
      'Zweryfikuj zgodność z normami PN-EN',
      'Sprawdź przejścia pożarowe przez ściany i stropy',
      'Zweryfikuj uszczelnienia ognioochronne (typ EI60+)',
      'Sprawdź wymiarowanie przekrojów kanałów wentylacji',
      'Zweryfikuj próbę rurociągów sprężonym powietrzem',
      'Sprawdź zasuwy i zawory na instalacji (typ, wymagania)',
      'Zweryfikuj prawidłowość oznaczeń elementów instalacji',
    ],
  },
  {
    id: 'termoizolacja-poddasza',
    name: 'Termoizolacja poddasza',
    description: 'Kontrola wykonania izolacji termicznej i paroizolacji poddasza',
    items: [
      'Sprawdź projekt izolacji (grubość wełny, wg WT2021)',
      'Zweryfikuj materiał izolacyjny (wełna mineralna λ ≤ 0,035)',
      'Sprawdź pierwszy layer wełny między krokwiami (szczelne wypełnienie)',
      'Zweryfikuj drugi layer wełny pod krokwiami (prostopadle)',
      'Sprawdź grubość łączną izolacji (min 30 cm dla WT2021)',
      'Zweryfikuj szczelność złączeń warstw wełny (bez mostków)',
      'Sprawdź folie paroizolacyjna (klasa Sd ≥ 5m)',
      'Zweryfikuj zakłady folii paroizolacyjnej (min 15cm, taśmowane)',
      'Sprawdź połączenie folii ze ścianami (taśma butylowa)',
      'Zweryfikuj brak uszkodzeń i dziur w folii',
      'Sprawdź szczelinę wentylacyjną za FWK (min 2cm)',
      'Zweryfikuj drożność kanałów wentylacyjnych pod dachem',
      'Sprawdź izolację okien dachowych (mansardowanie)',
    ],
  },
  {
    id: 'elewacja',
    name: 'Elewacja',
    description: 'Kontrola wykonania ocieplenia i tynku elewacyjnego metodą ETICS',
    items: [
      'Sprawdź projekt ocieplenia (grubość styropianu, typ)',
      'Zweryfikuj gatunek styropianu (EPS100 λ≤0,033 lub EPS150 cokół)',
      'Sprawdź przygotowanie podłoża (myjka, grunt)',
      'Zweryfikuj listwy startowe (poziom, mocowanie)',
      'Sprawdź klej do styropianu (aplikacja metodą obwodowo-punktową)',
      'Zweryfikuj przyklejenie płyt (min 40% powierzchni)',
      'Sprawdź układ płyt styropianu (mijankowy, odskok na narożnikach)',
      'Zweryfikuj kołkowanie styropianu (długość, ilość min 6 szt/m²)',
      'Sprawdź siatka zbrojąca (gramatura min 145 g/m²)',
      'Zweryfikuj głębokość zatopienia siatki w masie klejowej',
      'Sprawdź zakłady siatki na narożnikach (ukośne wstawki)',
      'Zweryfikuj czas sezonowania podkładu (min 72h)',
      'Sprawdź podkład tynkarski (kolor zbliżony do tynku)',
      'Zweryfikuj tynk elewacyjny (typ: silikonowy, mineralny)',
      'Sprawdź grubość tynku (zgodność z uziarnieniem)',
      'Zweryfikuj jednolitość faktury tynku (bez smug, odcieni)',
      'Sprawdź obróbki blacharskie (parapety, nakrywy)',
      'Zweryfikuj uszczelnienie połączeń elewacji z stolarką',
    ],
  },
]
